spring:
  application:
    name: kafka-producer
  kafka:
    producer:
      bootstrap-servers: localhost:29092,localhost:39092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true


  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/
      database: currency_symbols

producerService:
  topicName: coin_symbols
  groupId: consumerGroup


logging:
  level:
    root: INFO

server:
  port: 8082